#!/bin/bash

cd $HOME
wget http://dials.diamond.ac.uk/diamond_builds/dials-linux-x86_64.tar.xz -O - | tar xJ
cd dials-installer-dev
./install --nopycompile --verbose --prefix=..
cd ..

# Fix up build path
ln dials-dev* build_dials -s
