#!/bin/bash

cd $HOME
wget https://dials.diamond.ac.uk/diamond_builds/dials-linux-x86_64-conda3.tar.gz -O - | tar xz
cd dials-installer-dev
./install --nopycompile --verbose --prefix=..
cd ..

# Fix up build path
ln dials-dev* build_dials -s
